### PR TITLE
update alpine image from 3.12 to 3.14

### PR DESCRIPTION
**Pull request by georgeok**
fixes netdata/netdata#10903

### CODE REVIEW

**Comment by ilyam8** [comment]
I see we [had some problems with v3.13](https://github.com/netdata/helper-images/pull/101), but don't remember what the problems were.

**Comment by Ferroin** [comment]
> I see we [had some problems with v3.13](https://github.com/netdata/helper-images/pull/101), but don't remember what the problems were.

The issue is an interaction between the (1005 correctly implemented) time64 compatibility code in musl 1.2 and newer and the braindead behavior of runc to return `-EPERM` for syscalls it does not recognize instead of `-ENOSYS`. Essentially, the containers won’t run on older Docker hosts due to the syscalls that musl is trying to use (which it _should_ be getting `-ENOSYS` for on the systems in question) returning `-EPERM`.

I _think_ Ubuntu 18.04 and Debian 10 as Docker hosts are still affected by this, which means we can’t just blindly make this change. I’ll poke the analytics team to see if we have any data about actual distribution of Docker host platforms among our Docker images.

**Comment by Ferroin** [comment]
OK, based on anonymous statistics, more than half of our users are running Docker containers on Ubuntu 20.04. which is thankfully not affected by the issue. Next most common is ‘unknown’ for the host OS, which is problematic at best for us. The rest is a long tail of mostly Debian and Ubuntu versions, plus a few hundred CentOS users (7 _is_ affected by this issue, 8 is not AFAIK).

I’m probably going to have to discuss this with our product team because of that huge number of unknown systems.

**Review by Ferroin — DISMISSED** [review]

**Review by iigorkarpov — DISMISSED** [review]

**Comment by Ferroin** [comment]
@georgeok Could you update this to just jump straight to Alpine 3.15 since it’s out now (and ideally rebase on the latest master branch as well when you do so)? We’re planning on updating once v1.32.0 is out (later this week), but I’d rather not step through 3.14, and I do want to make sure you get credit for it.

**Comment by georgeok** [comment]
@Ferroin Yes sure, I've updated to alpine `3.15` 😁

**Pull request merged**
