### PR TITLE
Add package builder images for Fedora & CentOS.

### PR DESCRIPTION
**Pull request by Ferroin**
Same as #31, but for Fedora & CentOS.

The usage is identical to the Debian package builder images.

### CODE REVIEW

**Comment by prologic** [comment]
> Same as #31, but for Fedora & CentOS.

This may be a silly question; but are we 100% sure Fedora and CentOS are always and will always be identical? I've no experience with Fedora, but plenty with CentOS. Just ask'n :)

**Comment by Ferroin** [comment]
> > Same as #31, but for Fedora & CentOS.
> 
> This may be a silly question; but are we 100% sure Fedora and CentOS are always and will always be identical? I've no experience with Fedora, but plenty with CentOS. Just ask'n :)

The build process should be, and if it isn't I suspect that the Fedora team would consider that a bug worth fixing.

**Comment by prologic** [comment]
Testing with Fedora 30:

- Building the image [works](https://gist.github.com/prologic/bd6eef0ecefcc95b1209fb9bf133f6fb)
- Building the Agent [works](https://gist.github.com/prologic/7b422c7e9381aa1ce3701996e7a26e11)
- Testing the Agent [works](https://gist.github.com/prologic/bb521d68e3f09b19cf192c313c554ee9)

**Comment by prologic** [comment]
Some small tweaks in https://github.com/netdata/helper-images/pull/38

**Comment by prologic** [comment]
> The build process should be, and if it isn't I suspect that the Fedora team would consider that a bug worth fixing.

I soon discovered after saying this that CentOS and other RPM-based systems actually declare an `ID_LIKE`. So they're effectively all the same really or can be treated as such.

**Pull request merged**
