### PR TITLE
Add libyaml as a dependency

### PR DESCRIPTION
**Pull request by MrZammler**
Adds libyaml to our helper images.

### CODE REVIEW

**Comment by tkatsoulas** [comment]
We need to think a way to automatically update a new dependency on all the docker files. Manually adding may introduce friction (opening a issue with priority low) . 

CC @Ferroin

**Review by tkatsoulas — DISMISSED** [review]

**Comment by tkatsoulas** [comment]
@MrZammler 
please add 
```
yaml-dev
yaml-static
```
to our `static-builder/Dockerfile`

**Comment by MrZammler** [comment]
> @MrZammler please add
> 
> ```
> yaml-dev
> yaml-static
> ```
> 
> deps to our `static-builder/Dockerfile`

Done. I didn't add it initialy, I saw json-c was missing from there and I assumed our bundle would bundle it, but I guess this makes more sense.

**Comment by MrZammler** [comment]
> Our Docker images aren’t build statically, so unless we’re statically linking libyaml somehow for them, we also need the runtime library added to `base/Dockerfile`.

Thanks Austin, added `yaml` to base/Dockerfile (if I understood correctly).

**Review by tkatsoulas — APPROVED** [review]

**Review by Ferroin — APPROVED** [review]

**Pull request merged**
